### ISSUE TITLE
Markdown filter ignores format from template

### ISSUE THREAD

**Issue by Tagirijus** [christopher-ramirez/secretary#68]
Hi there,

I am not sure if this might be related to https://github.com/christopher-ramirez/secretary/issues/67

When using the `|markdown` filter, the output text in the document ignores the formatting from the odt-template file. It seems like it is using the default font and size instead.

**Comment by christopher-ramirez** [comment]
Hello,

The markdown filter indeed uses the document default text format for its output. What kind of format you would like to inherit to the outputted text?

**Comment by Tagirijus** [comment]
Hey Christopher, I expected that the format from the variables position in the template would be used - like it is, when you do not use the `markdown` filter.

**Comment by christopher-ramirez** [comment]
I understand that what you say is what would expect. But for a markdown output it's technically challenging to keep the format because the how Libreoffice internally manages the styles in the document. Most of the document is handled by multiple styles with random names. Is some like a CSS architecture.

**Comment by Tagirijus** [comment]
I see, what a bummer. Thanks for your reply, though!
